version: "3.7"
services:
  crawler:
    build:
      context: .
      dockerfile: docker/Dockerfile
    image: site_crawler
    container_name: site_crawler
    environment:
      TZ: "Asia/Tokyo"
      TARGET_URLS:
      SCRAPING_WORDS:
      SLACK_WEBHOOK_URL:
      LOGGING_LEVEL:
      OUTPUT_LOG_FILE_ENABLED: false
    logging:
      options:
        max-file: '3'
        max-size: 10m
    restart: always
